### PR TITLE
Rate Limits dont mean instant death.

### PR DESCRIPTION
**Pull request by brendanjerwin**

### CODE REVIEW

**Comment by brendanjerwin** [comment]
@mattatcha care to grant me repo admin so I can set up CI?

**Comment by mattatcha** [comment]
@brendanjerwin It doesn't let me make you an admin but I can transfer the repo to you if you want.

**Comment by brendanjerwin** [comment]
Alright then. That’ll work.

**Comment by mwarkentin** [comment]
+1, I'm still interested in seeing if this project can move forward. :)

**Pull request merged**
